---
- name: Install nginx, php
  hosts: all
  become: yes

  tasks:
  - name: enable requarments in amazon-linux extras
    shell: "amazon-linux-extras enable nginx1.12 php7.2 epel"
    become: yes

  - name: Install nginx
    yum:
      name: nginx
      update_cache: yes
      state: latest

  - name: Replace Index.html
    host: env_web
    ansible.builtin.shell: echo "<h1>It's Alive and running from $(hostname -f)<h/1>" > /usr/share/nginx/html/index.html

    # copy: 
    #    content: "<h1>It's Alive and running from $(hostname -f)<h/1>"
    #    dest: /usr/share/nginx/html/index.html

  - name: start/enable Nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Install php-fpm
    yum:
      name:
        - php-fpm
        - php-mbstring
        - php-xml
        - php-json
        - php-common
      state: latest

  - name: start/enable php-fpm
    service:
      name: php-fpm
      state: started
      enabled: yes


- name: Install mariadb and phpmyadmin
  hosts: env_db
  become: yes

  tasks:
  - name: Install mariadb
    yum:
      name:
        - mariadb
        - mariadb-server
      state: latest

  - name: start mariadb
    service:
      name: mariadb
      enabled: true
      state: started

  - name: Creates phpmyadmin directory
    file:
      path: /usr/share/nginx/html/phpmyadmin/
      state: directory

  - name: Setup phpMyAdmin
    ansible.builtin.unarchive:
      src: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
      dest: /usr/share/nginx/html/phpmyadmin
      extra_opts: [--strip-components=1]
      remote_src: yes
